[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { path = "../lib" }
config = "0.13"
env_logger = "0.10"
log = "0.4"
tokio = { version = "1.27", features = ["full"] }
error-stack = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
