[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0"
config = "0"
log = "0"
tokio = { version = "1", features = ["full"] }
lib = { path = "../lib" }
error-stack = "0.2.4"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
